root/home/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from home import views

app_name = 'home'
urlpatterns = [
  path('', views.index, name='index'),
  path('signin/', views.signin, name='signin'),
  path('signout/', views.signout, name='signout')
]

root/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('category/', include('category.urls', namespace='category')),
    path('product/', include('product.urls', namespace='product')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/product/urls.py
from django.urls import path

from product import views

app_name = 'product'
urlpatterns = [
  path('', views.index, name='index'),
  path('add', views.add, name='add'),
  path('edit/<int:id>', views.edit, name='edit'),
  path('delete/<int:id>', views.delete, name='delete'),
]

root/product/models.py
from django.db import models
from category.models import Category

class Product(models.Model):
  product_id = models.BigAutoField(primary_key=True)
  category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
  product_name = models.CharField(max_length=100, null=True)
  product_description = models.TextField(null=True)
  product_stock = models.IntegerField(null=True)
  product_image = models.ImageField(upload_to='product/', null=True, blank=True)
  product_created = models.DateTimeField(null=True, auto_now_add=True)
  product_modified = models.DateTimeField(null=True, auto_now=True)

  def __str__(self):
    return self.product_name

root/product/forms.py
from django import forms
from django.forms import ModelForm, fields, widgets
from product.models import Product
from django.utils.translation import gettext_lazy as _

class FormProduct(ModelForm):
  product_image = forms.FileInput(attrs={'required': False})

  class Meta:
    model = Product
    fields = ['category', 'product_name', 'product_description', 'product_stock', 'product_image']
    label = {
      'category' : _('Category'), 
      'product_name' : _('Name'),
      'product_description' : _('Description'),
      'product_stock' : _('Stock'),
      'product_image' : _('Image'),
    }
    widgets = {
      'category' : forms.Select({'class':'form-control'}),
      'product_name' : forms.TextInput({'class':'form-control'}),
      'product_description' : forms.Textarea({'class':'form-control'}),
      'product_stock' : forms.NumberInput({'class':'form-control'}),
      'product_image' : forms.FileInput({'class':'form-control'}),
    }

root/product/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from product.models import Product
from product.forms import FormProduct
import os


@login_required(login_url=settings.LOGIN_URL)
def index(request):
  data = {
    'title' : 'product-index',
    'data' : Product.objects.all(),
  }

  return render(request, 'product/index.html', data)

@login_required(login_url=settings.LOGIN_URL)
def add(request):
  if request.POST:
    form = FormProduct(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      messages.success(request, 'Data has been saved')
      return redirect('product:add')
    else:
      messages.error(request, form.errors)
      return redirect('product:add')

  else :
    data = {
      'title' : 'product-add',
      'form' : FormProduct(),
    }
    return render(request, 'product/add.html', data)

@login_required(login_url=settings.LOGIN_URL)
def edit(request, id):
  product = Product.objects.get(product_id=id)
  if request.POST:
    form = FormProduct(request.POST, request.FILES, instance=product)
    if form.is_valid():

      # deleting old uploaded image.
      product2 = Product.objects.get(product_id=id)
      image_path = product2.product_image.path
      if os.path.exists(image_path):
          os.remove(image_path)

      form.save()
      messages.success(request, 'Data updated successfully')
      return redirect('product:edit', id=id)
    else:
      messages.error(request, form.errors)
      return redirect('product:edit', id=id)

  else:
    data = {
      'title' : 'product-edit',
      'form' : FormProduct(instance=product),
      'product' : product,
    }
    return render(request, 'product/edit.html', data)

@login_required(login_url=settings.LOGIN_URL)
def delete(request, id):
  product = Product.objects.get(product_id=id)
  print(product.product_image.path)
  if len(product.product_image):
    os.remove(product.product_image.path)
  product.delete()
  messages.success(request, 'Data deleted successfully')
  return redirect('product:index')

root/product/templates/product/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'head.html' %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  {% include 'preloader.html' %}

  {% include 'navbar.html' %}

  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Product</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Product</a></li>
              <li class="breadcrumb-item active">Add</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                  {% if message.tags == 'success' %}
                    <div class="alert alert-success alert-dismissible">
                  {% else %}
                    <div class="alert alert-danger alert-dismissible">
                  {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Alert!</h5>
                    {{ message }}
                  </div>
                {% endfor %}
            {% endif %}
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="card card-info">

              <div class="card-header">
                <h3 class="card-title">Form Add</h3>
              </div>
              <!-- /.card-header -->


              
              <!-- form start -->
              <form action="{% url 'product:add' %}" method="post" enctype="multipart/form-data">

                <div class="card-body">
                  {% csrf_token %}

                  {% for field in form %}
                  <div class="form-group row">
                    <label for="_name_" class="col-sm-3 col-form-label" style="text-align: right;">{{ field.label_tag }}</label>
                    <div class="col-sm-6">
                      {{ field }}
                      {{ field.errors }}
                      {{ field.help_text }}
                    </div>
                  </div>
                  {% endfor %}

                </div>

                <!-- /.card-body -->
                <div class="card-footer">
                  <div class="form-group row">
                    <div class="col-md-6 col-sm-6 offset-md-3">
                      <a href="{% url 'product:index' %}">
                        <button type="button" class="btn btn-warning">Cancel</button>
                      </a>
                      <button type="reset" class="btn btn-info" id="_reset_">Reset</button>
                      <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                  </div>
                </div>
                <!-- /.card-footer -->
              
              </form>
            </div>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% include 'footer.html' %}

</div>
<!-- ./wrapper -->

{% include 'javascript.html' %}
</body>
</html>

root/product/templates/product/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'head.html' %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  {% include 'preloader.html' %}

  {% include 'navbar.html' %}

  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Product</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Product</a></li>
              <li class="breadcrumb-item active">Edit</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                  {% if message.tags == 'success' %}
                    <div class="alert alert-success alert-dismissible">
                  {% else %}
                    <div class="alert alert-danger alert-dismissible">
                  {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Alert!</h5>
                    {{ message }}
                  </div>
                {% endfor %}
            {% endif %}
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="card card-info">

              <div class="card-header">
                <h3 class="card-title">Form Add</h3>
              </div>
              <!-- /.card-header -->


              
              <!-- form start -->
              <form action="{% url 'product:edit' product.product_id %}" method="post" enctype="multipart/form-data">

                <div class="card-body">
                  {% csrf_token %}

                  {% for field in form %}
                  <div class="form-group row">
                    <label for="_name_" class="col-sm-3 col-form-label" style="text-align: right;">{{ field.label_tag }}</label>
                    <div class="col-sm-6">
                      {{ field }}
                      {{ field.errors }}
                      {{ field.help_text }}
                    </div>
                  </div>
                  {% endfor %}

                </div>

                <!-- /.card-body -->
                <div class="card-footer">
                  <div class="form-group row">
                    <div class="col-md-6 col-sm-6 offset-md-3">
                      <a href="{% url 'product:index' %}">
                        <button type="button" class="btn btn-warning">Cancel</button>
                      </a>
                      <button type="reset" class="btn btn-info" id="_reset_">Reset</button>
                      <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                  </div>
                </div>
                <!-- /.card-footer -->
              
              </form>
            </div>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% include 'footer.html' %}

</div>
<!-- ./wrapper -->

{% include 'javascript.html' %}
</body>
</html>

root/product/templates/product/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'head.html' %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  {% include 'preloader.html' %}

  {% include 'navbar.html' %}

  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Product</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Product</a></li>
              <li class="breadcrumb-item active">Table</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
              {% for message in messages %}
                {% if message.tags == 'success' %}
                  <div class="alert alert-success alert-dismissible">
                {% else %}
                  <div class="alert alert-danger alert-dismissible">
                {% endif %}
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <h5><i class="icon fas fa-check"></i> Alert!</h5>
                  {{ message }}
                </div>
              {% endfor %}
          {% endif %}
        </div>
      </div>
      
      <div class="row">
        <div class="col-12">

          <div class="card card-info">
            <div class="card-header">
              <h3 class="card-title">Add</h3>
              
              <div class="card-tools">
                <ul class="nav nav-pills ml-auto">
                  <li class="nav-item">
                    <a href="{% url 'product:add' %}">
                      <button type="button" class="btn btn-warning btn-sm"><i class="fa fa-plus-square"></i> Add</button>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <!-- /.card-header -->

            <div class="card-body">
              <table id="_table_" class="table table-bordered table-hover table-striped" width="100%">
                <thead>
                <tr>
                  <th>No</th>
                  <th>Category</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Stock</th>
                  <th>Image</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                  {% for dt in data %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ dt.category }}</td>
                    <td>{{ dt.product_name }}</td>
                    <td>{{ dt.product_description }}</td>
                    <th>{{ dt.product_stock }}</th>
                    <th>
                      {% if dt.product_image %}
                        <img src="{{ dt.product_image.url }}" alt="" width="90px">
                      {% endif %}
                    </th>
                    <td>
                      <a href="{% url 'product:edit' dt.product_id %}" data-toggle="tooltip" title="Edit">
                        <button type="button" class="btn btn-warning"><i class="fa fa-edit"></i></button>
                      </a>
                      <a href="{% url 'product:delete' dt.product_id %}" onclick="return confirm('Are you sure you want to delete this item?');" data-toggle="tooltip" title="Delete">
                          <button type="button" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                      </a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>

  {% include 'footer.html' %}

</div>
<!-- ./wrapper -->

{% include 'javascript.html' %}

<script>
  $('#_table_').DataTable()
</script>
</body>
</html>