root/category/urls.py
from django.urls import path

from category import views

app_name = 'category'
urlpatterns = [
  path('', views.index, name='index'),
  path('add', views.add, name='add'),
  path('edit/<int:id>', views.edit, name='edit'),
  path('delete/<int:id>', views.delete, name='delete'),
]

root/home/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from home import views

app_name = 'home'
urlpatterns = [
  path('', views.index, name='index'),
  path('signin/', views.signin, name='signin'),
  path('signout/', views.signout, name='signout')
]

root/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('category/', include('category.urls', namespace='category')),
    path('product/', include('product.urls', namespace='product')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/category/models.py
from django.db import models

class Category(models.Model):
  category_id = models.BigAutoField(primary_key=True)
  category_name = models.CharField(max_length=50, null=True)
  category_description = models.TextField(null=True)

  def __str__(self):
    return self.category_name

root/category/forms.py
from django import forms
from django.forms import ModelForm
from category.models import Category
from django.utils.translation import gettext_lazy as _

class FormCategory(ModelForm):
  class Meta:
    model = Category
    fields = '__all__'
    labels = {
      'category_name': _('Name'),
      'category_description': _('Description'),
    }
    widgets = {
      'category_name' : forms.TextInput({'class':'form-control'}),
      'category_description' : forms.TextInput({'class':'form-control'})
    }

root/category/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from category.models import Category
from category.forms import FormCategory
from django.contrib.auth.decorators import login_required
from django.conf import settings

@login_required(login_url=settings.LOGIN_URL)
def index(request):
  data = {
    'title' : 'category-index',
    'data' : Category.objects.all(),
  }
  return render(request, 'category/index.html', data)

@login_required(login_url=settings.LOGIN_URL)
def add(request):
  if request.POST:
    form = FormCategory(request.POST)
    if form.is_valid():
      form.save()
      messages.success(request, 'Data has been saved')
      return redirect('category:add')
    else:
      messages.error(request, form.errors)
      return redirect('category:add')

  else :
    data = {
      'title' : 'category-add',
      'form' : FormCategory(),
    }
    return render(request, 'category/add.html', data)

@login_required(login_url=settings.LOGIN_URL)
def edit(request, id):
  category = Category.objects.get(category_id=id)
  if request.POST:
    form = FormCategory(request.POST, instance=category)
    if form.is_valid():
      form.save()
      messages.success(request, 'Data updated successfully')
      return redirect('category:edit', id=id)
    else:
      messages.error(request, form.errors)
      return redirect('category:edit', id=id)

  else:
    data = {
      'title' : 'category-edit',
      'form' : FormCategory(instance=category),
      'category' : category,
    }
    return render(request, 'category/edit.html', data)

@login_required(login_url=settings.LOGIN_URL)
def delete(request, id):
  category = Category.objects.filter(category_id=id)
  category.delete()
  messages.success(request, 'Data deleted successfully')
  return redirect('category:index')

root/category/templates/category/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'head.html' %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  {% include 'preloader.html' %}

  {% include 'navbar.html' %}

  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Category</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Category</a></li>
              <li class="breadcrumb-item active">Add</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                  {% if message.tags == 'success' %}
                    <div class="alert alert-success alert-dismissible">
                  {% else %}
                    <div class="alert alert-danger alert-dismissible">
                  {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Alert!</h5>
                    {{ message }}
                  </div>
                {% endfor %}
            {% endif %}
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="card card-info">

              <div class="card-header">
                <h3 class="card-title">Form Add</h3>
              </div>
              <!-- /.card-header -->


              
              <!-- form start -->
              <form action="{% url 'category:add' %}" method="post">

                <div class="card-body">
                  {% csrf_token %}

                  {% for field in form %}
                  <div class="form-group row">
                    <label for="_name_" class="col-sm-3 col-form-label" style="text-align: right;">{{ field.label_tag }}</label>
                    <div class="col-sm-6">
                      {{ field }}
                      {{ field.errors }}
                      {{ field.help_text }}
                    </div>
                  </div>
                  {% endfor %}

                </div>

                <!-- /.card-body -->
                <div class="card-footer">
                  <div class="form-group row">
                    <div class="col-md-6 col-sm-6 offset-md-3">
                      <a href="{% url 'category:index' %}">
                        <button type="button" class="btn btn-warning">Cancel</button>
                      </a>
                      <button type="reset" class="btn btn-info" id="_reset_">Reset</button>
                      <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                  </div>
                </div>
                <!-- /.card-footer -->
              
              </form>
            </div>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% include 'footer.html' %}

</div>
<!-- ./wrapper -->

{% include 'javascript.html' %}
</body>
</html>

root/category/templates/category/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'head.html' %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  {% include 'preloader.html' %}

  {% include 'navbar.html' %}

  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Category</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                  {% if message.tags == 'success' %}
                    <div class="alert alert-success alert-dismissible">
                  {% else %}
                    <div class="alert alert-danger alert-dismissible">
                  {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Alert!</h5>
                    {{ message }}
                  </div>
                {% endfor %}
            {% endif %}
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="card card-info">

              <div class="card-header">
                <h3 class="card-title">Form Add</h3>
              </div>
              <!-- /.card-header -->


              
              <!-- form start -->
              <form action="{% url 'category:edit' category.category_id %}" method="post">

                <div class="card-body">
                  {% csrf_token %}

                  {% for field in form %}
                  <div class="form-group row">
                    <label for="_name_" class="col-sm-3 col-form-label" style="text-align: right;">{{ field.label_tag }}</label>
                    <div class="col-sm-6">
                      {{ field }}
                      {{ field.errors }}
                      {{ field.help_text }}
                    </div>
                  </div>
                  {% endfor %}

                </div>

                <!-- /.card-body -->
                <div class="card-footer">
                  <div class="form-group row">
                    <div class="col-md-6 col-sm-6 offset-md-3">
                      <a href="{% url 'category:index' %}">
                        <button type="button" class="btn btn-warning">Cancel</button>
                      </a>
                      <button type="reset" class="btn btn-info" id="_reset_">Reset</button>
                      <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                  </div>
                </div>
                <!-- /.card-footer -->
              
              </form>
            </div>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% include 'footer.html' %}

</div>
<!-- ./wrapper -->

{% include 'javascript.html' %}
</body>
</html>

root/category/templates/category/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'head.html' %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  {% include 'preloader.html' %}

  {% include 'navbar.html' %}

  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Category</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Category</a></li>
              <li class="breadcrumb-item active">Table</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
              {% for message in messages %}
                {% if message.tags == 'success' %}
                  <div class="alert alert-success alert-dismissible">
                {% else %}
                  <div class="alert alert-danger alert-dismissible">
                {% endif %}
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <h5><i class="icon fas fa-check"></i> Alert!</h5>
                  {{ message }}
                </div>
              {% endfor %}
          {% endif %}
        </div>
      </div>
      
      <div class="row">
        <div class="col-12">

          <div class="card card-info">
            <div class="card-header">
              <h3 class="card-title">Add</h3>
              
              <div class="card-tools">
                <ul class="nav nav-pills ml-auto">
                  <li class="nav-item">
                    <a href="{% url 'category:add' %}">
                      <button type="button" class="btn btn-warning btn-sm"><i class="fa fa-plus-square"></i> Add</button>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <!-- /.card-header -->

            <div class="card-body">
              <table id="_table_" class="table table-bordered table-hover table-striped" width="100%">
                <thead>
                <tr>
                  <th>No</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                  {% for dt in data %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ dt.category_name }}</td>
                    <td>{{ dt.category_description }}</td>
                    <td>
                      <a href="{% url 'category:edit' dt.category_id %}" data-toggle="tooltip" title="Edit">
                        <button type="button" class="btn btn-warning"><i class="fa fa-edit"></i></button>
                      </a>
                      <a href="{% url 'category:delete' dt.category_id %}" onclick="return confirm('Are you sure you want to delete this item?');" data-toggle="tooltip" title="Delete">
                          <button type="button" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                      </a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->

        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>

  {% include 'footer.html' %}

</div>
<!-- ./wrapper -->

{% include 'javascript.html' %}

<script>
  $('#_table_').DataTable()
</script>
</body>
</html>